
springdoc:
  title: Example API
  version: 0.0.0
  description: This is an example API 
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    syntaxHighlight.activated: false


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example
    username: test
    password: test
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true